# Generated by Django 4.1 on 2022-08-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='MyApps',
        ),
    ]
